### ISSUE TITLE
Can't change enabled options for existing entries in repeater fields

### ISSUE THREAD

**Issue by Zielgestalt** [pauloamgomes/Cockpit-CustomComponents#5]
Thanks for this wonderful plugin. Really important if you work with a lot of components and external content editors.

In a collection I have a repeater field with this options:

`{
  "fields": [
    {
      "type": "set",
      "name": "sections",
      "label": "Section",
      "options": {
        "fields": [
          {
            "name": "headline",
            "type": "text",
            "label": "Headline"
          },
          {
            "name": "elements",
            "type": "layout",
            "label": "Elements",
            "options": {
              "enabled": [
                "alert",
                "list",
                "headline"
              ]
            }
          }
        ]
      }
    }
  ]
}`

Now I want to allow more layout components in the elements field and changed the configuration of the collection. This works for new sections, but in existing entries the list of enabled components didn't change.

**Comment by pauloamgomes** [comment]
Hi @Zielgestalt , thats an issue with Cockpit repeater field has the set field structure will be part of the entry.. check below:

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/102261/71669496-b717ef00-2d64-11ea-8af8-d115a33bc9bc.png">

the same will not happen for example if you use a set instead of a repeater, a way to fix that is to create a cli command that iterate of all entries of that collection and update the field definition

**Comment by Zielgestalt** [comment]
Ok, thank you!
